// Generated by schema site tooling. Do not edit directly.
export default {
  unocss: {
    nuxtLayers: true,
    preflight: true,
    configFile: "./uno.config.ts"
  },
  devServer: {
    port: 9274,
    host: "0.0.0.0"
  },
  vite: {
    server: {
      allowedHosts: [
        "raven.local"
      ],
      origin: "https://raven.local:4443",
      hmr: {
        protocol: "wss",
        host: "raven.local",
        clientPort: 4443,
        path: "/__vitews",
        port: 45017
      }
    }
  },
  extends: [
    "./layers/schema-core",
    "./layers/helios"
  ],
  modules: [
    "@unocss/nuxt"
  ],
  compatibilityDate: "2026-01-30"
};
